wandb_version: 1

discount_factor:
  desc: null
  value: 0.98
estimation_step:
  desc: null
  value: 20
target_update_freq:
  desc: null
  value: 1000
optminizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.00016
max_epoch:
  desc: null
  value: 500
step_per_epoch:
  desc: null
  value: 20000
step_per_collect:
  desc: null
  value: 400
episode_per_test:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 256
update_per_step:
  desc: null
  value: 0.02
tn_eps_max:
  desc: null
  value: 0.1
ts_eps_max:
  desc: null
  value: 0.0
max_cycles:
  desc: null
  value: 500
x_size:
  desc: null
  value: 16
y_size:
  desc: null
  value: 16
shared_reward:
  desc: null
  value: false
n_evaders:
  desc: null
  value: 30
n_pursuers:
  desc: null
  value: 8
obs_range:
  desc: null
  value: 7
n_catch:
  desc: null
  value: 2
freeze_evaders:
  desc: null
  value: false
tag_reward:
  desc: null
  value: 0.01
catch_reward:
  desc: null
  value: 5.0
urgency_reward:
  desc: null
  value: -0.1
surround:
  desc: null
  value: true
constraint_window:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700264846.317763
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.10.9
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      9:
        2: tianshou
      13: windows-amd64
