wandb_version: 1

discount_factor:
  desc: null
  value: 0.98
estimation_step:
  desc: null
  value: 20
target_update_freq:
  desc: null
  value: 256
optminizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.0001
max_epoch:
  desc: null
  value: 500
step_per_epoch:
  desc: null
  value: 1280
step_per_collect:
  desc: null
  value: 50
episode_per_test:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
update_per_step:
  desc: null
  value: 0.03333333333333333
tn_eps_max:
  desc: null
  value: 0.95
ts_eps_max:
  desc: null
  value: 0.0
string_length:
  desc: null
  value: 6
n_agents:
  desc: null
  value: 2
seed:
  desc: null
  value: 0
m_steps:
  desc: null
  value: 128
sp:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700114254.686897
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.11.6
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      9:
        2: tianshou
      13: windows-amd64
